// <auto-generated />
using System;
using API_Usuario.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Usuario.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20250627141845_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Usuario.Models.Acompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataFeedBack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeedEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeedFuncion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Funcionarioid")
                        .HasColumnType("char(36)");

                    b.Property<string>("PontosAltos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PontosBaixos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Funcionarioid");

                    b.ToTable("Acompanhamentos");
                });

            modelBuilder.Entity("API_Usuario.Models.Desligamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataDesligamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeedDesligamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Funcionarioid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("funcionarioid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isGrave")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Funcionarioid");

                    b.HasIndex("funcionarioid");

                    b.ToTable("Desligamentos");
                });

            modelBuilder.Entity("API_Usuario.Models.FitCultural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Funcionarioid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Funcionarioid");

                    b.ToTable("FitCulturals");
                });

            modelBuilder.Entity("API_Usuario.Models.Funcionario", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataAdmi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataDemi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataNasci")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Funcionarioid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Funcionarioid");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("API_Usuario.Models.MotivoDesligamentos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Funcionarioid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("desligamentoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Funcionarioid");

                    b.HasIndex("desligamentoId");

                    b.ToTable("MotivoDesligamentos");
                });

            modelBuilder.Entity("API_Usuario.Models.Acompanhamento", b =>
                {
                    b.HasOne("API_Usuario.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Funcionarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("API_Usuario.Models.Desligamento", b =>
                {
                    b.HasOne("API_Usuario.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Funcionarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Usuario.Models.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("API_Usuario.Models.FitCultural", b =>
                {
                    b.HasOne("API_Usuario.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Funcionarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("API_Usuario.Models.Funcionario", b =>
                {
                    b.HasOne("API_Usuario.Models.Funcionario", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("Funcionarioid");
                });

            modelBuilder.Entity("API_Usuario.Models.MotivoDesligamentos", b =>
                {
                    b.HasOne("API_Usuario.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Funcionarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Usuario.Models.Desligamento", "desligamento")
                        .WithMany()
                        .HasForeignKey("desligamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("desligamento");
                });

            modelBuilder.Entity("API_Usuario.Models.Funcionario", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
